/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/sample.glb -o ./src/compoenents/Sample.jsx 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Sample(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/sample.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="hiker_girl">
          <mesh
            name="Cube022"
            geometry={nodes.Cube022.geometry}
            material={materials.skin}
          />
          <mesh
            name="Cube022_1"
            geometry={nodes.Cube022_1.geometry}
            material={materials.pants}
          />
          <mesh
            name="Cube022_2"
            geometry={nodes.Cube022_2.geometry}
            material={materials.leather}
          />
          <mesh
            name="Cube022_3"
            geometry={nodes.Cube022_3.geometry}
            material={materials.boots}
          />
          <mesh
            name="Cube022_4"
            geometry={nodes.Cube022_4.geometry}
            material={materials.shirt}
          />
          <mesh
            name="Cube022_5"
            geometry={nodes.Cube022_5.geometry}
            material={materials.shirt_white}
          />
          <mesh
            name="Cube022_6"
            geometry={nodes.Cube022_6.geometry}
            material={materials.hair}
          />
          <mesh
            name="Cube022_7"
            geometry={nodes.Cube022_7.geometry}
            material={materials["black "]}
          />
          <mesh
            name="Cube022_8"
            geometry={nodes.Cube022_8.geometry}
            material={materials.backpack}
          />
          <mesh
            name="Cube022_9"
            geometry={nodes.Cube022_9.geometry}
            material={materials.backpack_01}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/sample.glb");
